name: Publish Stubs
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Vital for pushing to GitHub Packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # References the server in settings.xml

      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Consumer
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.STUB_TOKEN }}" \
            https://api.github.com/repos/gayatripande/spring-consumer/dispatches \
            -d '{"event_type": "stubs-updated"}'